# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # Use a versão mais recente
  hooks:
  - id: trailing-whitespace    # Remove espaços em branco no final
  - id: end-of-file-fixer     # Garante uma nova linha no final do arquivo
  - id: check-yaml            # Verifica a sintaxe de arquivos YAML
  - id: check-added-large-files # Impede o commit de arquivos muito grandes
